[package]
name = "tectonopedia"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "^4", features = ["derive"] }
serde = { version = "^1.0", features = ["derive"] }
string-interner = "^0.14"
tectonic = "^0.11"
tectonic_bridge_core = "^0.3"
tectonic_errors = "^0.2"
tectonic_status_base = "^0.2"
termcolor = "^1.1"
threadpool = "^1.8"
toml = "^0.5"
walkdir = "^2"
