[package]
name = "tectonopedia"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "^4", features = ["derive"] }
tectonic = "^0.11"
tectonic_bridge_core = "^0.3"
tectonic_errors = "^0.2"
tectonic_status_base = "^0.2"
threadpool = "^1.8"
walkdir = "^2"
